import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LogoICon } from "@/assets/svgs/common";
import { Button } from "@heroui/button";
import { Menu } from "@/components";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="flex h-screen w-full flex-row">
					<div className="flex h-screen w-1/6 flex-col items-center justify-center gap-12 bg-[#D3D3D3] p-4">
						<LogoICon
							width={200}
							height={200}
						/>
						<span className="font-semibold">Welcome back, John</span>
						<Menu />
						<div className="my-2 flex w-full flex-col items-center gap-4">
							<Button
								size="md"
								className="w-1/2 bg-secondary font-semibold text-white"
							>
								Sign out
							</Button>
						</div>
					</div>
					<div className="flex-1">{children}</div>
				</div>
			</body>
		</html>
	);
}
